export const productActions = {
    FETCH_ALL_PRODUCTS_START:"FETCH_ALL_PRODUCTS_START",
    FETCH_ALL_PRODUCTS_SUCCESS:"FETCH_ALL_PRODUCTS_SUCCESS",
    FETCH_ALL_PRODUCTS_FAILED:"FETCH_ALL_PRODUCTS_FAILED"
}